steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA
      - ./server

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --vpc-connector=${_VPC_CONNECTOR}
      - --set-env-vars=^|^DB_HOST=${_DB_HOST}|DB_PORT=5432|DB_NAME=${_DB_NAME}|NODE_ENV=production|GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}|KINTONE_DOMAIN=${_KINTONE_DOMAIN}|KINTONE_KPI_APP_ID=${_KINTONE_KPI_APP_ID}|KINTONE_MASTER_APP_ID=${_KINTONE_MASTER_APP_ID}|KINTONE_ORGANIZATION_APP_ID=${_KINTONE_ORGANIZATION_APP_ID}|GOOGLE_DRIVE_FOLDER_ID=${_GOOGLE_DRIVE_FOLDER_ID}|CORS_ORIGINS=${_CORS_ORIGINS}
      - --set-secrets=DB_USER=${_DB_USER_SECRET}:latest,DB_PASSWORD=DB_PASSWORD:latest,JWT_SECRET=JWT_SECRET:latest,KINTONE_KPI_API_KEY=KINTONE_KPI_API_KEY:latest,KINTONE_MASTER_API_KEY=KINTONE_MASTER_API_KEY:latest,KINTONE_ORGANIZATION_API_KEY=KINTONE_ORGANIZATION_API_KEY:latest

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format='value(status.url)' | xargs -I {} sh -c 'printf "VITE_API_URL=%s\nVITE_GOOGLE_CLIENT_ID=%s\n" "{}" "${_GOOGLE_CLIENT_ID}" > client/.env.production'

  - name: 'node:20'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd client
        npm ci
        npm run build

  - name: 'gcr.io/ggpc-kpi-system/firebase'
    args: ['deploy', '--project=${_FIREBASE_PROJECT}', '--only=hosting']

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA'

substitutions:
  _REGION: asia-southeast1
  _REPOSITORY: cloud-run-source-deploy
  _IMAGE: kpi-backend
  _SERVICE_NAME: kpi-backend-test
  _DB_NAME: pms-db-staging
  _DB_HOST: 10.8.0.3
  _DB_USER_SECRET: TEST_DB_USER
  _VPC_CONNECTOR: kpi-vpc-con
  _FIREBASE_PROJECT: ggpc-kpi-test
  _CORS_ORIGINS: https://ggpc-kpi-test.web.app,https://ggpc-kpi-test.firebaseapp.com
  _GOOGLE_CLIENT_ID: 390302333724-hk4tc6tqr08vb8pcp15ts8jtq1if5htb.apps.googleusercontent.com
  _KINTONE_DOMAIN: vez7o26y38rb.cybozu.com
  _KINTONE_KPI_APP_ID: '1910'
  _KINTONE_MASTER_APP_ID: '111'
  _KINTONE_ORGANIZATION_APP_ID: '204'
  _GOOGLE_DRIVE_FOLDER_ID: 1pZWpmM6U32evDmGuzYHn8t5u0BgvzXjS
